export const mainnetIbcChannels = [
  {
    key: "1",
    source_channel: "channel-1",
    destination_chain: "Osmosis",
    destination_chainid: "osmosis-1",
    destination_channel: "channel-87",
    known_operators:
      "Cros-nest, Mandragora, CryptoCrew, AutoStake, Lavender.Five Nodes, Tedcrypto.io, Golden Ratio Staking, Zenscape, Polkachu",
  },
  {
    key: "2",
    source_channel: "channel-43",
    destination_chain: "Band",
    destination_chainid: "laozi-mainnet",
    destination_channel: "channel-96",
    known_operators: "CryptoCrew, Architect Nodes, Zenscape",
  },
  {
    key: "3",
    source_channel: "channel-37",
    destination_chain: "Cosmos",
    destination_chainid: "cosmoshub-4",
    destination_channel: "channel-400",
    known_operators: "CryptoCrew, Mandragora, Zenscape, ChainTools, Cros-nest, Polkachu",
  },
  {
    key: "4",
    source_channel: "channel-34",
    destination_chain: "Axelar",
    destination_chainid: "axelar-dojo-1",
    destination_channel: "channel-37",
    known_operators: "Zenscape, Mandragora, Cros-nest, Polkachu",
  },
  {
    key: "5",
    source_channel: "channel-18",
    destination_chain: "Juno",
    destination_chainid: "juno-1",
    destination_channel: "channel-36",
    known_operators: "Cros-nest, CryptoCrew, EZStaking.io Relayer, ChainTools, Polkachu",
  },
  {
    key: "6",
    source_channel: "channel-31",
    destination_chain: "Kujira",
    destination_chainid: "kaiyo-1",
    destination_channel: "channel-18",
    known_operators: "Zenscape, CryptoCrew, ChainTools, Cros-nest, Polkachu",
  },
  {
    key: "7",
    source_channel: "channel-33",
    destination_chain: "OKC",
    destination_chainid: "exchain-66",
    destination_channel: "channel-10",
    known_operators: "Zenscape",
  },
  {
    key: "8",
    source_channel: "channel-23",
    destination_chain: "Gravity Bridge",
    destination_chainid: "gravity-bridge-3",
    destination_channel: "channel-21",
    known_operators: "CryptoCrew, Cros-nest, Zenscape, Polkachu",
  },
  {
    key: "9",
    source_channel: "channel-57",
    destination_chain: "Persistence",
    destination_chainid: "core-1",
    destination_channel: "channel-71",
    known_operators: "Architect Nodes, Paranormal Bros, Cros-nest, Polkachu",
  },
  {
    key: "10",
    source_channel: "channel-52",
    destination_chain: "Akash",
    destination_chainid: "akash-1",
    destination_channel: "channel-55",
    known_operators: "Polkachu, Zenscape",
  },
  {
    key: "11",
    source_channel: "channel-35",
    destination_chain: "Evmos",
    destination_chainid: "evmos_9001-2",
    destination_channel: "channel-26",
    known_operators: "Mandragora, Architect Nodes, Polkachu",
  },
  {
    key: "12",
    source_channel: "channel-51",
    destination_chain: "Luna",
    destination_chainid: "phoenix-1",
    destination_channel: "channel-39",
    known_operators: "Zenscape",
  },
  {
    key: "13",
    source_channel: "channel-49",
    destination_chain: "Crescent",
    destination_chainid: "crescent-1",
    destination_channel: "channel-28",
    known_operators: "Zenscape, B-Harvest",
  },
  {
    key: "14",
    source_channel: "channel-45",
    destination_chain: "Stride",
    destination_chainid: "stride-1",
    destination_channel: "channel-49",
    known_operators: "Cros-nest, Architect Nodes, Mandragora, Zenscape",
  },
  {
    key: "15",
    source_channel: "channel-59",
    destination_chain: "Asset mantle",
    destination_chainid: "mantle-1",
    destination_channel: "channel-17",
    known_operators: "Cros-nest",
  },
  {
    key: "16",
    source_channel: "channel-58",
    destination_chain: "Canto",
    destination_chainid: "canto_7700-1",
    destination_channel: "channel-7",
    known_operators: "Zenscape, Cros-nest",
  },
  {
    key: "17",
    source_channel: "channel-61",
    destination_chain: "chihuahua",
    destination_chainid: "chihuahua-1",
    destination_channel: "channel-37",
    known_operators: "Cros-nest, Stakelab, Polkachu",
  },
];
